env: "local"
#storage_path:
http_server:
  address: "localhost:2005"
  timeout: 4s
  iddle_timeout: 60s
#docker configuration
services:
 postgres:
    image: postgres:15-alpine
    container_name: market_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: Mihail
      POSTGRES_PASSWORD: Chupa-lupa
      POSTGRES_DB: marketplace
    ports:
      - "1863:1863"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
