services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: Mihail
      POSTGRES_PASSWORD: Chupa-lupa
      POSTGRESS_HOST: 127.0.0.1
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"  # Правильный формат: "хост:контейнер"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
